const KEY='parkflow-kku-reports-v1';
const esc=value=>String(value??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const seed=[{id:'RW-240912',title:'จอดรถขวางทางลาด อาคารเรียนรวม 3',type:'จอดรถกีดขวาง / ผิดพื้นที่',place:'อาคารเรียนรวม 3',date:'12 ก.ย. 2026',status:'กำลังตรวจสอบ',ai:92,image:'PARKING'},{id:'RW-240821',title:'จอดรถจักรยานยนต์บนทางเท้า',type:'จอดบนทางเท้า',place:'ถนนกัลปพฤกษ์',date:'21 ส.ค. 2026',status:'ดำเนินการแล้ว',ai:95,image:'SIDEWALK'}];
let reports=JSON.parse(localStorage.getItem(KEY)||'null')||seed;const isParkingReport=r=>!/(no helmet|helmet|หมวกกันน็อค|หมวกนิรภัย|ไม่สวมหมวก)/i.test(`${r.description||''} ${r.title||''} ${r.type||''}`);reports=reports.filter(isParkingReport);const save=()=>localStorage.setItem(KEY,JSON.stringify(reports));
window.addEventListener('cloud-reports-loaded',e=>{reports=e.detail.filter(isParkingReport).map(r=>({dbId:r.id,id:(r.id||'').slice(0,8),title:r.description,type:'รายงานจากระบบ',place:r.location||'ไม่ระบุสถานที่',date:new Date(r.created_at).toLocaleDateString('th-TH',{day:'2-digit',month:'short',year:'numeric'}),status:{PENDING:'กำลังตรวจสอบ',UNDER_REVIEW:'กำลังตรวจสอบ',APPROVED:'ตรวจสอบแล้ว',REJECTED:'ไม่เข้าเกณฑ์',REQUEST_INFO:'ขอข้อมูลเพิ่ม'}[r.status]||'กำลังตรวจสอบ',ai:Number(r.ai_confidence)||0,image:'EVIDENCE',reporterName:r.reporter?.name||'ไม่ระบุชื่อ',reporterEmail:r.reporter?.email||'ไม่ระบุอีเมล',evidenceUrl:r.evidence_url||null}));save();renderHome();renderHistory();if(e.detail.admin)renderAdmin()});
const views=[...document.querySelectorAll('.view')],nav=[...document.querySelectorAll('.nav-item')];
function go(id){views.forEach(v=>v.classList.toggle('active-view',v.id===id));nav.forEach(n=>n.classList.toggle('active',n.dataset.view===id));const titles={home:'สวัสดี, Tanakrit 👋',report:'แจ้งรายงานใหม่',history:'รายการของฉัน',admin:'Admin review'};document.querySelector('#page-title').innerHTML=titles[id]||titles.home;if(id==='home')renderHome();if(id==='history')renderHistory();if(id==='admin')renderAdmin();window.scrollTo({top:0,behavior:'smooth'})}nav.forEach(n=>n.onclick=()=>go(n.dataset.view));document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>go(b.dataset.go));
const upload=document.querySelector('#upload'),file=upload.querySelector('input');upload.onclick=()=>file.click();file.onchange=()=>{if(file.files[0]){upload.querySelector('b').textContent='✓ '+file.files[0].name;upload.dataset.filename=file.files[0].name}};const datetime=document.querySelector('[name="incidentDatetime"]');if(datetime)datetime.value=new Date(Date.now()-new Date().getTimezoneOffset()*60000).toISOString().slice(0,16);const gps=document.querySelector('#gps-button');if(gps)gps.onclick=()=>navigator.geolocation?.getCurrentPosition(p=>{document.querySelector('[name="latitude"]').value=p.coords.latitude;document.querySelector('[name="longitude"]').value=p.coords.longitude;gps.textContent='✓ บันทึกพิกัดแล้ว'},()=>toast('ไม่สามารถเข้าถึงตำแหน่งได้'));
function toast(m){const t=document.querySelector('#toast');t.textContent='✓ '+m;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),3200)}
document.querySelector('#report-form').onsubmit=async e=>{e.preventDefault();const fd=new FormData(e.target),type=fd.get('type')||'อื่น ๆ',details=fd.get('details')||'รายละเอียดรายงาน',place=fd.get('place')||'ไม่ระบุสถานที่',local={id:'RW-'+String(Date.now()).slice(-6),title:type+' — '+details.slice(0,65),type,place,date:new Date().toLocaleDateString('th-TH',{day:'2-digit',month:'short',year:'numeric'}),status:'กำลังตรวจสอบ',ai:0,image:(upload.dataset.filename||'EVIDENCE').slice(0,12).toUpperCase()};const submit=e.target.querySelector('button[type=submit]');submit.disabled=true;submit.textContent='กำลังส่งรายงาน…';try{if(!window.saveCloudReport)throw Error('ระบบยังไม่ได้เชื่อมต่อ');await window.saveCloudReport({title:details,plate_number:fd.get('plateNumber'),location:place,incident_datetime:fd.get('incidentDatetime'),latitude:fd.get('latitude'),longitude:fd.get('longitude')},file.files[0]||null);reports.unshift(local);save();e.target.reset();if(datetime)datetime.value=new Date(Date.now()-new Date().getTimezoneOffset()*60000).toISOString().slice(0,16);delete upload.dataset.filename;upload.querySelector('b').innerHTML='ลากไฟล์มาวางที่นี่ หรือ <u>เลือกไฟล์</u>';toast('ส่งรายงานและบันทึกข้อมูลแล้ว');setTimeout(()=>go('history'),650)}catch(err){toast('ส่งรายงานไม่สำเร็จ: '+(err.message||'กรุณาลองใหม่'));}finally{submit.disabled=false;submit.innerHTML='ส่งรายงานให้ทีมงาน <span>→</span>'}};
function row(r){return `<div class="report-row"><div class="report-thumb t1">${esc(r.image)}</div><div class="report-info"><b>${esc(r.title)}</b><small>#${esc(r.id)} · ${esc(r.date)} · ${esc(r.place)}</small></div><span class="status ${r.status==='กำลังตรวจสอบ'?'review':'done'}">${esc(r.status)}</span><span class="chev">›</span></div>`}
function renderHome(){const l=document.querySelector('.report-list');if(l)l.innerHTML=reports.slice(0,3).map(row).join('');const s=document.querySelectorAll('.stat strong');if(s.length){s[0].textContent=reports.length;s[1].textContent=String(reports.filter(r=>r.status==='กำลังตรวจสอบ').length).padStart(2,'0');s[2].textContent=String(reports.filter(r=>r.status!=='กำลังตรวจสอบ').length).padStart(2,'0')}}
function renderHistory(){const g=document.querySelector('.history-grid');if(!g)return;g.innerHTML=reports.slice(0,8).map(r=>`<div class="history-card"><span class="status ${r.status==='กำลังตรวจสอบ'?'review':'done'}">${r.status}</span><h3>#${r.id}</h3><p>${r.title}</p><small>ส่งเมื่อ ${r.date} · AI confidence ${r.ai}%</small>${r.status==='กำลังตรวจสอบ'?'<div class="progress"><i style="width:68%"></i></div><small>AI ตรวจแล้ว · รอ Admin ยืนยัน</small>':'<div class="resolved">✓ ทีมงานยืนยันข้อมูลและแจ้งผู้ขับขี่แล้ว</div>'}</div>`).join('')}
function renderAdmin(){const p=document.querySelector('.review-panel');if(!p)return;const head=p.querySelector('.panel-head'),pending=reports.filter(r=>r.status==='กำลังตรวจสอบ'),stats=document.querySelectorAll('.admin-stats b');if(stats.length){stats[0].textContent=String(pending.length).padStart(2,'0');stats[1].textContent=String(reports.filter(r=>r.ai>80).length).padStart(2,'0');stats[2].textContent=String(reports.filter(r=>r.status==='ตรวจสอบแล้ว').length).padStart(2,'0');stats[3].textContent='—'}p.innerHTML='';p.appendChild(head);if(!pending.length){p.insertAdjacentHTML('beforeend','<div class="queue"><div class="queue-body"><h3>ไม่มีรายการที่รอตรวจสอบ</h3><p>คิวทั้งหมดได้รับการจัดการแล้ว</p></div></div>');return}pending.slice(0,8).forEach(r=>p.insertAdjacentHTML('beforeend',`<div class="queue" data-id="${esc(r.dbId||r.id)}"><div class="queue-image">${r.evidenceUrl?`<img src="${esc(r.evidenceUrl)}" alt="หลักฐานรายงาน ${esc(r.id)}">`:esc(r.image)}<br><small>AI ${esc(r.ai)}%</small></div><div class="queue-body"><span class="status review">รอ Admin ยืนยัน</span><h3>${esc(r.title)}</h3><p>${esc(r.place)} · ${esc(r.date)}</p><p class="reporter-detail">ผู้แจ้ง: <b>${esc(r.reporterName)}</b> · ${esc(r.reporterEmail)}</p><div class="ai-check">✦ AI ตรวจพบ: <b>${esc(r.type)}</b> <span>ความมั่นใจ ${esc(r.ai)}%</span></div></div><div class="queue-actions"><button class="approve">✓ ยืนยันข้อมูล</button><button class="reject">ไม่เข้าเกณฑ์</button></div></div>`));p.querySelectorAll('.approve').forEach(b=>b.onclick=()=>update(b,'ตรวจสอบแล้ว','ยืนยันข้อมูลแล้ว'));p.querySelectorAll('.reject').forEach(b=>b.onclick=()=>update(b,'ไม่เข้าเกณฑ์','ส่งกลับแล้ว'))}
async function update(b,status,msg){const r=reports.find(x=>(x.dbId||x.id)===b.closest('.queue').dataset.id);if(!r)return;const old=r.status;b.disabled=true;try{if(!window.updateCloudReportStatus)throw Error('ระบบฐานข้อมูลยังไม่พร้อม');await window.updateCloudReportStatus(r.dbId||r.id,{ 'ตรวจสอบแล้ว':'APPROVED','ไม่เข้าเกณฑ์':'REJECTED'}[status]||'REQUEST_INFO');r.status=status;save();toast(msg);renderAdmin()}catch(e){toast('บันทึกสถานะไม่สำเร็จ: '+e.message);b.disabled=false;r.status=old}}
renderHome();
const loginButton=document.querySelector('#google-login');if(loginButton)loginButton.onclick=()=>window.startKKULogin?.();
const logoutButtons=[document.querySelector('#logout-sidebar'),document.querySelector('#logout-top')].filter(Boolean);logoutButtons.forEach(b=>b.onclick=()=>window.logoutKKU?.());
