import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';

// Supabase URL and anon key are safe for browser use when Row Level Security is enabled.
// Never put the service_role key here.
const SUPABASE_URL='https://zjolbhatwstmxcojznyd.supabase.co';
const SUPABASE_ANON_KEY='sb_publishable_V_JnaRXLYFjNrDysOFK5pA_5bCpyHXP';
const ADMIN_EMAIL='tanakrit.k@kkumail.com';
const TESTER_EMAIL='tanakritk21@gmail.com';
const configured=!SUPABASE_URL.includes('YOUR_')&&!SUPABASE_ANON_KEY.includes('YOUR_');
const supabase=configured?createClient(SUPABASE_URL,SUPABASE_ANON_KEY):null;
window.kkuSupabase=supabase;
const gate=document.querySelector('#login-gate'),error=document.querySelector('#login-error'),shell=document.querySelector('.shell');
window.startKKULogin=async()=>{if(!configured){error.textContent='ระบบกำลังตั้งค่า กรุณากลับมาใหม่ภายหลัง';return}await supabase.auth.signInWithOAuth({provider:'google',options:{redirectTo:location.origin+location.pathname,queryParams:{hd:'kkumail.com'}}})};
window.logoutKKU=async()=>{if(supabase){const {error:logoutError}=await supabase.auth.signOut();if(logoutError){console.error(logoutError);return}}window.currentKKUUser=null;document.body.classList.add('auth-required');gate.style.display='flex';shell.style.visibility='hidden';};
if(!configured){error.textContent='ระบบกำลังตั้งค่า กรุณากลับมาใหม่ภายหลัง';}
if(supabase){supabase.auth.onAuthStateChange(async(_event,session)=>{const user=session?.user;if(!user){window.currentKKUUser=null;document.body.classList.add('auth-required');gate.style.display='flex';shell.style.visibility='hidden';return}const email=(user.email||'').toLowerCase();const isKKU=email.endsWith('@kkumail.com')||email.endsWith('@kku.ac.th');const isTester=email===TESTER_EMAIL;if(!isKKU&&!isTester){await supabase.auth.signOut();error.textContent='บัญชีนี้ไม่ได้รับอนุญาตให้เข้าใช้งาน';return}window.currentKKUUser=user;const fields={id:user.id,email,name:user.user_metadata?.full_name||user.user_metadata?.name||email,role:email.endsWith('@kku.ac.th')?'staff':isTester?'tester':'student'};let profileResult=await supabase.from('profiles').select('*').eq('id',user.id).maybeSingle();if(!profileResult.data&&!profileResult.error)profileResult=await supabase.from('profiles').insert(fields).select('*').single();if(profileResult.error){console.warn('Profile unavailable:',profileResult.error.message);error.textContent='โหลดสิทธิ์ผู้ใช้ไม่สำเร็จ กรุณา Logout แล้ว Login ใหม่';return}window.currentKKUProfile=profileResult.data;const role=window.currentKKUProfile.role||'student';document.body.classList.remove('auth-required');gate.style.display='none';shell.style.visibility='visible';const p=document.querySelector('.profile small');if(p)p.textContent=(role==='admin'||role==='super_admin'?'Admin · ':role==='tester'?'Tester · ':role==='staff'?'บุคลากร · ':'นักศึกษา · ')+email;const name=document.querySelector('.profile b');if(name)name.textContent=user.user_metadata?.name||user.user_metadata?.full_name||email.split('@')[0];const topEmail=document.querySelector('#account-email');if(topEmail)topEmail.textContent=email;const topAvatar=document.querySelector('#logout-top .avatar');if(topAvatar)topAvatar.textContent=(email.split('@')[0].slice(0,2)||'KK').toUpperCase();const adminNav=document.querySelector('[data-view="admin"]');if(adminNav)adminNav.style.display=role==='admin'||role==='super_admin'?'flex':'none';if(window.loadCloudReports)window.loadCloudReports()});}
window.loadCloudReports=async()=>{if(!supabase||!window.currentKKUUser)return;const admin=window.currentKKUProfile?.role==='admin'||window.currentKKUProfile?.role==='super_admin';let query=admin?supabase.from('reports').select('*,reporter:profiles!reports_reporter_id_fkey(name,email)').order('created_at',{ascending:false}):supabase.from('reports').select('*').eq('reporter_id',window.currentKKUUser.id).order('created_at',{ascending:false});const {data,error:loadError}=await query;if(loadError){console.warn('Cloud reports unavailable:',loadError.message);return}const reportsWithEvidence=await Promise.all((data||[]).map(async r=>{if(!admin||!r.evidence_path)return r;const signed=await supabase.storage.from('evidence').createSignedUrl(r.evidence_path,900);return {...r,evidence_url:signed.data?.signedUrl||null}}));window.dispatchEvent(new CustomEvent('cloud-reports-loaded',{detail:reportsWithEvidence,admin}));};
window.updateCloudReportStatus=async(id,status)=>{if(!supabase||!window.currentKKUUser||!['APPROVED','REJECTED','REQUEST_INFO'].includes(status))throw Error('ไม่สามารถแก้ไขสถานะได้');const {data,error}=await supabase.from('reports').update({status,reviewed_by:window.currentKKUUser.id,reviewed_at:new Date().toISOString()}).eq('id',id).select().single();if(error)throw error;return data};
window.decideCloudReport=async(id,status,action,note='')=>{if(!supabase||!window.currentKKUUser||!['APPROVED','REJECTED','REQUEST_INFO'].includes(status))throw Error('ไม่สามารถดำเนินการได้');const {data:report,error:updateError}=await supabase.from('reports').update({status,reviewed_by:window.currentKKUUser.id,reviewed_at:new Date().toISOString()}).eq('id',id).select('*').single();if(updateError)throw updateError;let result='บันทึกผลตรวจสอบแล้ว';if(status==='APPROVED'&&action==='PENALTY'){const {data:rule}=await supabase.from('penalty_rules').select('id,points,fine_amount').eq('violation_type',report.violation_type||'').eq('active',true).maybeSingle();const {data:vehicle}=report.plate_number?await supabase.from('vehicle_registry').select('id').eq('plate_number',report.plate_number).eq('active',true).maybeSingle():{data:null};const {error}=await supabase.from('penalties').insert({vehicle_id:vehicle?.id||null,report_id:id,rule_id:rule?.id||null,points:rule?.points??5,fine_amount:rule?.fine_amount??0,reason:note||'ยืนยันการจอดรถจักรยานยนต์ผิดระเบียบ'});if(error)throw error;result='ยืนยันและสร้างบทลงโทษแล้ว'}if(status==='APPROVED'&&action==='EMAIL'){let recipient=null;if(report.plate_number){const {data:vehicle}=await supabase.from('vehicle_registry').select('owner_email').eq('plate_number',report.plate_number).eq('active',true).maybeSingle();recipient=vehicle?.owner_email||null}const {error}=await supabase.from('notification_queue').insert({report_id:id,recipient_email:recipient,subject:'แจ้งผลการตรวจสอบการจอดรถจักรยานยนต์ KKU ParkFlow',body:`ผลการตรวจสอบ: ${report.description}\nรายละเอียดเพิ่มเติม: ${note||'-'}\nช่องทางอุทธรณ์: ติดต่อหน่วยงานดูแลพื้นที่ของมหาวิทยาลัย`,status:recipient?'QUEUED':'NO_RECIPIENT'});if(error)throw error;result=recipient?'ยืนยันและเข้าคิวส่ง Gmail แล้ว':'ยืนยันแล้ว แต่ยังไม่พบอีเมลผู้รับ จึงยังส่ง Gmail ไม่ได้'}const {error:auditError}=await supabase.from('audit_logs').insert({actor_id:window.currentKKUUser.id,action:'REPORT_DECISION',entity_type:'report',entity_id:id,metadata:{status,action:action||'NONE',note:note||'',follow_up:result}});if(auditError)throw auditError;return {report,result}};
window.saveCloudReport=async(report,file)=>{if(!supabase||!window.currentKKUUser)throw Error('ต้องตั้งค่า Supabase และเข้าสู่ระบบก่อน');let evidence_path=null;if(file){if(!['image/jpeg','image/png'].includes(file.type)||file.size>10*1024*1024)throw Error('รองรับเฉพาะ JPG/PNG ขนาดไม่เกิน 10MB');const safeName=file.name.replace(/[^a-zA-Z0-9._-]/g,'_');evidence_path=`${window.currentKKUUser.id}/${crypto.randomUUID()}-${safeName}`;const up=await supabase.storage.from('evidence').upload(evidence_path,file,{contentType:file.type,upsert:false});if(up.error)throw up.error}const {data,error:dbError}=await supabase.from('reports').insert({reporter_id:window.currentKKUUser.id,plate_number:report.plate_number||null,violation_type:report.violation_type||null,description:report.title,location:report.location||null,incident_datetime:report.incident_datetime||new Date().toISOString(),latitude:report.latitude?Number(report.latitude):null,longitude:report.longitude?Number(report.longitude):null,evidence_path,status:'PENDING'}).select().single();if(dbError){if(evidence_path)await supabase.storage.from('evidence').remove([evidence_path]);throw dbError}if(evidence_path){const analysis=await supabase.functions.invoke('analyze-report',{body:{reportId:data.id}});if(analysis.data?.analysis)data.ai_confidence=analysis.data.analysis.confidence;if(analysis.error)console.warn('AI analysis is not configured or unavailable:',analysis.error.message)}return data};
