import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';

// Supabase URL and anon key are safe for browser use when Row Level Security is enabled.
// Never put the service_role key here.
const SUPABASE_URL='https://zjolbhatwstmxcojznyd.supabase.co';
const SUPABASE_ANON_KEY='sb_publishable_V_JnaRXLYFjNrDysOFK5pA_5bCpyHXP';
const ADMIN_EMAIL='tanakritk21@gmail.com';
const configured=!SUPABASE_URL.includes('YOUR_')&&!SUPABASE_ANON_KEY.includes('YOUR_');
const supabase=configured?createClient(SUPABASE_URL,SUPABASE_ANON_KEY):null;
window.kkuSupabase=supabase;
const gate=document.querySelector('#login-gate'),error=document.querySelector('#login-error'),shell=document.querySelector('.shell');
window.startKKULogin=async()=>{if(!configured){error.textContent='ระบบกำลังตั้งค่า กรุณากลับมาใหม่ภายหลัง';return}await supabase.auth.signInWithOAuth({provider:'google',options:{redirectTo:location.origin+location.pathname,queryParams:{hd:'kkumail.com'}}})};
window.logoutKKU=async()=>{if(supabase){const {error:logoutError}=await supabase.auth.signOut();if(logoutError){console.error(logoutError);return}}window.currentKKUUser=null;document.body.classList.add('auth-required');gate.style.display='flex';shell.style.visibility='hidden';};
if(!configured){error.textContent='ระบบกำลังตั้งค่า กรุณากลับมาใหม่ภายหลัง';}
if(supabase){supabase.auth.onAuthStateChange(async(_event,session)=>{const user=session?.user;if(!user){window.currentKKUUser=null;document.body.classList.add('auth-required');gate.style.display='flex';shell.style.visibility='hidden';return}const email=(user.email||'').toLowerCase();const isKKU=email.endsWith('@kkumail.com')||email.endsWith('@kku.ac.th');if(!isKKU&&email!==ADMIN_EMAIL){await supabase.auth.signOut();error.textContent='บัญชีนี้ไม่ได้รับอนุญาตให้เข้าใช้งาน';return}window.currentKKUUser=user;const role=email===ADMIN_EMAIL?'admin':'student';const profileResult=await supabase.from('profiles').upsert({id:user.id,email,name:user.user_metadata?.full_name||user.user_metadata?.name||email,role},{onConflict:'id'}).select().single();window.currentKKUProfile=profileResult.data||{email,role};document.body.classList.remove('auth-required');gate.style.display='none';shell.style.visibility='visible';const p=document.querySelector('.profile small');if(p)p.textContent=(role==='admin'?'Admin · ':'นักศึกษา · ')+email;const name=document.querySelector('.profile b');if(name)name.textContent=user.user_metadata?.name||user.user_metadata?.full_name||email.split('@')[0];const adminNav=document.querySelector('[data-view="admin"]');if(adminNav)adminNav.style.display=role==='admin'?'flex':'none';if(window.loadCloudReports)window.loadCloudReports()});}
window.loadCloudReports=async()=>{if(!supabase||!window.currentKKUUser)return;const admin=window.currentKKUProfile?.role==='admin'||window.currentKKUProfile?.role==='super_admin';let query=supabase.from('reports').select('*').order('created_at',{ascending:false});if(!admin)query=query.eq('reporter_id',window.currentKKUUser.id);const {data,error:loadError}=await query;if(loadError){console.warn('Cloud reports unavailable:',loadError.message);return}window.dispatchEvent(new CustomEvent('cloud-reports-loaded',{detail:data||[],admin}));};
window.updateCloudReportStatus=async(id,status)=>{if(!supabase||!window.currentKKUUser||!['APPROVED','REJECTED','REQUEST_INFO'].includes(status))throw Error('ไม่สามารถแก้ไขสถานะได้');const {data,error}=await supabase.from('reports').update({status,reviewed_by:window.currentKKUUser.id,reviewed_at:new Date().toISOString()}).eq('id',id).select().single();if(error)throw error;return data};
window.saveCloudReport=async(report,file)=>{if(!supabase||!window.currentKKUUser)throw Error('ต้องตั้งค่า Supabase และเข้าสู่ระบบก่อน');let evidence_path=null;if(file){const safeName=file.name.replace(/[^a-zA-Z0-9._-]/g,'_');evidence_path=`${window.currentKKUUser.id}/${crypto.randomUUID()}-${safeName}`;const up=await supabase.storage.from('evidence').upload(evidence_path,file,{contentType:file.type,upsert:false});if(up.error)throw up.error}const {data,error:dbError}=await supabase.from('reports').insert({reporter_id:window.currentKKUUser.id,plate_number:report.plate_number||null,description:report.title,incident_datetime:new Date().toISOString(),evidence_path,status:'PENDING'}).select().single();if(dbError)throw dbError;return data};
