create table if not exists public.profiles (id uuid primary key references auth.users(id) on delete cascade, email text not null, name text, role text not null default 'student' check (role in ('student','staff','admin','super_admin')), created_at timestamptz default now());
create table if not exists public.reports (id uuid primary key default gen_random_uuid(), reporter_id uuid not null references public.profiles(id), plate_number text, description text not null, incident_datetime timestamptz not null, latitude numeric, longitude numeric, evidence_path text, status text not null default 'PENDING' check (status in ('PENDING','UNDER_REVIEW','APPROVED','REJECTED','REQUEST_INFO')), ai_confidence numeric, ai_flags jsonb default '[]', reviewed_by uuid references public.profiles(id), reviewed_at timestamptz, created_at timestamptz default now());
alter table public.reports add column if not exists latitude numeric;
alter table public.reports add column if not exists longitude numeric;
create table if not exists public.vehicle_registry (id uuid primary key default gen_random_uuid(), plate_number text unique not null, owner_name text not null, owner_email text, owner_user_id uuid references public.profiles(id), active boolean not null default true, created_at timestamptz default now());
create table if not exists public.penalty_rules (id uuid primary key default gen_random_uuid(), violation_type text unique not null, points integer not null default 0, fine_amount numeric not null default 0, threshold_points integer not null default 10, active boolean not null default true, created_at timestamptz default now());
create table if not exists public.penalties (id uuid primary key default gen_random_uuid(), vehicle_id uuid references public.vehicle_registry(id), report_id uuid not null references public.reports(id), points integer not null default 0, fine_amount numeric not null default 0, reason text not null, created_at timestamptz default now());
create table if not exists public.appeals (id uuid primary key default gen_random_uuid(), report_id uuid not null references public.reports(id), appellant_id uuid not null references public.profiles(id), reason text not null, status text not null default 'PENDING' check (status in ('PENDING','UNDER_REVIEW','APPROVED','REJECTED')), decision_note text, decided_by uuid references public.profiles(id), decided_at timestamptz, created_at timestamptz default now());
create table if not exists public.audit_logs (id bigserial primary key, actor_id uuid references public.profiles(id), action text not null, entity_type text not null, entity_id uuid, metadata jsonb default '{}'::jsonb, created_at timestamptz default now());
alter table public.vehicle_registry enable row level security; alter table public.penalty_rules enable row level security; alter table public.penalties enable row level security; alter table public.appeals enable row level security; alter table public.audit_logs enable row level security;
create policy "admins manage vehicle registry" on public.vehicle_registry for all using (public.is_admin()) with check (public.is_admin());
create policy "admins manage penalty rules" on public.penalty_rules for all using (public.is_admin()) with check (public.is_admin());
create policy "users read own penalties" on public.penalties for select using (exists (select 1 from public.vehicle_registry v where v.id=vehicle_id and v.owner_user_id=auth.uid()) or public.is_admin());
create policy "users create own appeals" on public.appeals for insert with check (auth.uid()=appellant_id);
create policy "users read own appeals" on public.appeals for select using (auth.uid()=appellant_id or public.is_admin());
create policy "admins manage appeals" on public.appeals for update using (public.is_admin()) with check (public.is_admin());
create policy "admins read audit logs" on public.audit_logs for select using (public.is_admin());
insert into public.penalty_rules (violation_type,points,fine_amount,threshold_points) values ('จอดรถกีดขวาง / ผิดพื้นที่',5,0,10),('จอดขวางทางเข้าออก',5,0,10),('จอดบนทางเท้า',5,0,10),('จอดกีดขวางรถคันอื่น',5,0,10) on conflict (violation_type) do nothing;
alter table public.profiles enable row level security; alter table public.reports enable row level security;
create or replace function public.is_admin() returns boolean language sql security definer set search_path = public as $$ select exists (select 1 from public.profiles where id=auth.uid() and role in ('admin','super_admin')); $$;
create policy "users read own profile" on public.profiles for select using (auth.uid()=id);
create policy "users create own profile" on public.profiles for insert with check (auth.uid()=id);
create policy "users update own profile" on public.profiles for update using (auth.uid()=id) with check (auth.uid()=id);
create or replace function public.prevent_role_escalation() returns trigger language plpgsql security definer set search_path = public as $$ begin if old.role is distinct from new.role and current_user not in ('postgres','supabase_admin') and coalesce(auth.role(),'') <> 'service_role' then raise exception 'role can only be changed by a server administrator'; end if; return new; end; $$;
drop trigger if exists profiles_role_guard on public.profiles;
create trigger profiles_role_guard before update on public.profiles for each row execute function public.prevent_role_escalation();
create policy "users read own reports" on public.reports for select using (auth.uid()=reporter_id);
create policy "users create own reports" on public.reports for insert with check (auth.uid()=reporter_id);
create policy "admins read all reports" on public.reports for select using (public.is_admin());
create policy "admins update reports" on public.reports for update using (public.is_admin()) with check (public.is_admin());
insert into storage.buckets(id,name,public) values('evidence','evidence',false) on conflict(id) do nothing;
create policy "users upload own evidence" on storage.objects for insert to authenticated with check (bucket_id='evidence' and (storage.foldername(name))[1]=auth.uid()::text);
create policy "users read own evidence" on storage.objects for select to authenticated using (bucket_id='evidence' and (storage.foldername(name))[1]=auth.uid()::text);
