create table if not exists public.profiles (id uuid primary key references auth.users(id) on delete cascade, email text not null, name text, role text not null default 'student' check (role in ('student','staff','admin','super_admin','tester')), created_at timestamptz default now());
alter table public.profiles drop constraint if exists profiles_role_check;
alter table public.profiles add constraint profiles_role_check check (role in ('student','staff','admin','super_admin','tester'));
create table if not exists public.reports (id uuid primary key default gen_random_uuid(), reporter_id uuid not null references public.profiles(id), plate_number text, violation_type text, description text not null, incident_datetime timestamptz not null, latitude numeric, longitude numeric, evidence_path text, status text not null default 'PENDING' check (status in ('PENDING','UNDER_REVIEW','APPROVED','REJECTED','REQUEST_INFO')), ai_confidence numeric, ai_flags jsonb default '[]', reviewed_by uuid references public.profiles(id), reviewed_at timestamptz, created_at timestamptz default now());
alter table public.reports add column if not exists violation_type text;
alter table public.reports add column if not exists latitude numeric;
alter table public.reports add column if not exists longitude numeric;
alter table public.reports add column if not exists location text;
create table if not exists public.vehicle_registry (id uuid primary key default gen_random_uuid(), plate_number text unique not null, owner_name text not null, owner_email text, owner_user_id uuid references public.profiles(id), active boolean not null default true, created_at timestamptz default now());
create table if not exists public.penalty_rules (id uuid primary key default gen_random_uuid(), violation_type text unique not null, points integer not null default 0, fine_amount numeric not null default 0, threshold_points integer not null default 10, active boolean not null default true, created_at timestamptz default now());
create table if not exists public.penalties (id uuid primary key default gen_random_uuid(), vehicle_id uuid references public.vehicle_registry(id), report_id uuid not null references public.reports(id), rule_id uuid references public.penalty_rules(id), points integer not null default 0, fine_amount numeric not null default 0, reason text not null, created_at timestamptz default now());
alter table public.penalties add column if not exists rule_id uuid references public.penalty_rules(id);
create table if not exists public.appeals (id uuid primary key default gen_random_uuid(), report_id uuid not null references public.reports(id), appellant_id uuid not null references public.profiles(id), reason text not null, status text not null default 'PENDING' check (status in ('PENDING','UNDER_REVIEW','APPROVED','REJECTED')), decision_note text, decided_by uuid references public.profiles(id), decided_at timestamptz, created_at timestamptz default now());
create table if not exists public.audit_logs (id bigserial primary key, actor_id uuid references public.profiles(id), action text not null, entity_type text not null, entity_id uuid, metadata jsonb default '{}'::jsonb, created_at timestamptz default now());
create table if not exists public.notification_queue (id uuid primary key default gen_random_uuid(), report_id uuid not null references public.reports(id), recipient_email text, subject text not null, body text not null, status text not null default 'QUEUED' check (status in ('QUEUED','SENT','FAILED','NO_RECIPIENT')), created_at timestamptz default now(), sent_at timestamptz);
create table if not exists public.mock_gmail_contacts (id uuid primary key default gen_random_uuid(), email text not null, display_name text not null, active boolean not null default true, created_by uuid references public.profiles(id), created_at timestamptz not null default now());
create unique index if not exists mock_gmail_contacts_email_idx on public.mock_gmail_contacts (lower(email));
create table if not exists public.mock_gmail_messages (id uuid primary key default gen_random_uuid(), report_id uuid references public.reports(id) on delete set null, recipient_email text not null, recipient_name text, subject text not null, body text not null, status text not null default 'SENT' check (status in ('DRAFT','SENT','FAILED')), sent_by uuid references public.profiles(id), sent_at timestamptz, created_at timestamptz not null default now());
create index if not exists mock_gmail_messages_sent_at_idx on public.mock_gmail_messages (sent_at desc);
create or replace function public.is_admin() returns boolean language sql security definer set search_path = public as $$ select exists (select 1 from public.profiles where id=auth.uid() and role in ('admin','super_admin')); $$;
create or replace function public.handle_new_auth_user() returns trigger language plpgsql security definer set search_path = public as $$ declare user_email text := lower(coalesce(new.email,'')); user_name text := coalesce(new.raw_user_meta_data->>'full_name',new.raw_user_meta_data->>'name',split_part(user_email,'@',1)); user_role text := case when user_email='tanakritk21@gmail.com' then 'tester' when user_email like '%@kku.ac.th' then 'staff' else 'student' end; begin insert into public.profiles(id,email,name,role) values(new.id,user_email,user_name,user_role) on conflict(id) do update set email=excluded.email,name=coalesce(nullif(excluded.name,''),public.profiles.name); return new; end; $$;
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users for each row execute function public.handle_new_auth_user();
insert into public.profiles(id,email,name,role) select u.id,lower(u.email),coalesce(u.raw_user_meta_data->>'full_name',u.raw_user_meta_data->>'name',split_part(lower(u.email),'@',1)),case when lower(u.email)='tanakritk21@gmail.com' then 'tester' when lower(u.email) like '%@kku.ac.th' then 'staff' else 'student' end from auth.users u left join public.profiles p on p.id=u.id where p.id is null and u.email is not null and (lower(u.email) like '%@kkumail.com' or lower(u.email) like '%@kku.ac.th' or lower(u.email)='tanakritk21@gmail.com') on conflict(id) do nothing;
alter table public.vehicle_registry enable row level security; alter table public.penalty_rules enable row level security; alter table public.penalties enable row level security; alter table public.appeals enable row level security; alter table public.audit_logs enable row level security; alter table public.notification_queue enable row level security;
alter table public.mock_gmail_contacts enable row level security; alter table public.mock_gmail_messages enable row level security;
create policy "admins manage vehicle registry" on public.vehicle_registry for all using (public.is_admin()) with check (public.is_admin());
create policy "admins manage penalty rules" on public.penalty_rules for all using (public.is_admin()) with check (public.is_admin());
create policy "admins manage penalties" on public.penalties for all using (public.is_admin()) with check (public.is_admin());
create policy "users read own penalties" on public.penalties for select using (exists (select 1 from public.vehicle_registry v where v.id=vehicle_id and v.owner_user_id=auth.uid()) or public.is_admin());
create policy "users create own appeals" on public.appeals for insert with check (auth.uid()=appellant_id);
create policy "users read own appeals" on public.appeals for select using (auth.uid()=appellant_id or public.is_admin());
create policy "admins manage appeals" on public.appeals for update using (public.is_admin()) with check (public.is_admin());
create policy "admins read audit logs" on public.audit_logs for select using (public.is_admin());
create policy "admins create audit logs" on public.audit_logs for insert with check (public.is_admin());
create policy "admins manage notification queue" on public.notification_queue for all using (public.is_admin()) with check (public.is_admin());
drop policy if exists "admins manage mock gmail contacts" on public.mock_gmail_contacts;
create policy "admins manage mock gmail contacts" on public.mock_gmail_contacts for all using (public.is_admin()) with check (public.is_admin());
drop policy if exists "admins manage mock gmail messages" on public.mock_gmail_messages;
create policy "admins manage mock gmail messages" on public.mock_gmail_messages for all using (public.is_admin()) with check (public.is_admin());
insert into public.penalty_rules (violation_type,points,fine_amount,threshold_points) values ('จอดรถกีดขวาง / ผิดพื้นที่',5,0,10),('จอดขวางทางเข้าออก',5,0,10),('จอดบนทางเท้า',5,0,10),('จอดกีดขวางรถคันอื่น',5,0,10) on conflict (violation_type) do nothing;
alter table public.profiles enable row level security; alter table public.reports enable row level security;
create or replace function public.is_admin() returns boolean language sql security definer set search_path = public as $$ select exists (select 1 from public.profiles where id=auth.uid() and role in ('admin','super_admin')); $$;
create policy "users read own profile" on public.profiles for select using (auth.uid()=id);
drop policy if exists "admins read reporter profiles" on public.profiles;
create policy "admins read reporter profiles" on public.profiles for select using (public.is_admin());
create policy "users create own profile" on public.profiles for insert with check (auth.uid()=id);
create policy "users update own profile" on public.profiles for update using (auth.uid()=id) with check (auth.uid()=id);
create or replace function public.prevent_role_escalation() returns trigger language plpgsql security definer set search_path = public as $$ begin if old.role is distinct from new.role and current_user not in ('postgres','supabase_admin') and coalesce(auth.role(),'') <> 'service_role' then raise exception 'role can only be changed by a server administrator'; end if; return new; end; $$;
drop trigger if exists profiles_role_guard on public.profiles;
create trigger profiles_role_guard before update on public.profiles for each row execute function public.prevent_role_escalation();
create policy "users read own reports" on public.reports for select using (auth.uid()=reporter_id);
create policy "users create own reports" on public.reports for insert with check (auth.uid()=reporter_id);
create policy "admins read all reports" on public.reports for select using (public.is_admin());
create policy "admins update reports" on public.reports for update using (public.is_admin()) with check (public.is_admin());
insert into storage.buckets(id,name,public) values('evidence','evidence',false) on conflict(id) do nothing;
create policy "users upload own evidence" on storage.objects for insert to authenticated with check (bucket_id='evidence' and (storage.foldername(name))[1]=auth.uid()::text);
create policy "users read own evidence" on storage.objects for select to authenticated using (bucket_id='evidence' and (storage.foldername(name))[1]=auth.uid()::text);
drop policy if exists "admins read all evidence" on storage.objects;
create policy "admins read all evidence" on storage.objects for select to authenticated using (bucket_id='evidence' and public.is_admin());
