require('dotenv').config();
const path=require('path'),jwt=require('jsonwebtoken'),express=require('express'),cookieParser=require('cookie-parser'),helmet=require('helmet'),cors=require('cors'),crypto=require('crypto'),{OAuth2Client}=require('google-auth-library'),{Pool}=require('pg'),multer=require('multer'),rateLimit=require('express-rate-limit'),nodemailer=require('nodemailer');
const app=express(), pool=new Pool({connectionString:process.env.DATABASE_URL}); const oauth=new OAuth2Client(process.env.GOOGLE_CLIENT_ID,process.env.GOOGLE_CLIENT_SECRET,process.env.GOOGLE_REDIRECT_URI); const domains=(process.env.ALLOWED_EMAIL_DOMAINS||'kkumail.com,kku.ac.th').split(',').map(x=>x.trim().toLowerCase());
app.use(helmet({contentSecurityPolicy:false}));app.use(cors({origin:['http://localhost:4000','http://localhost:5173'],credentials:true}));app.use(express.json({limit:'1mb'}));app.use(cookieParser());app.use(express.static(path.join(__dirname,'..')));
const reportLimit=rateLimit({windowMs:86400000,max:5,standardHeaders:true,message:{error:'Daily report limit reached'}});const upload=multer({storage:multer.memoryStorage(),limits:{fileSize:(+process.env.MAX_UPLOAD_MB||10)*1024*1024},fileFilter:(req,file,cb)=>cb(null,['image/jpeg','image/png'].includes(file.mimetype))});
function csrf(req,res,next){if(['GET','HEAD','OPTIONS'].includes(req.method))return next();if(!req.cookies.csrf||req.cookies.csrf!==req.get('x-csrf-token'))return res.status(403).json({error:'CSRF validation failed'});next()}
function auth(req,res,next){try{const raw=req.cookies.access_token;if(!raw)return res.status(401).json({error:'Authentication required'});req.user=jwt.verify(raw,process.env.SESSION_SECRET);next()}catch(e){res.status(401).json({error:'Invalid session'})}}
app.get('/auth/google',(_,res)=>{if(!process.env.GOOGLE_CLIENT_ID||process.env.GOOGLE_CLIENT_ID.startsWith('your-'))return res.status(503).send('Google OAuth ยังไม่ได้ตั้งค่า กรุณาตรวจสอบไฟล์ .env');const state=crypto.randomBytes(24).toString('hex');res.cookie('oauth_state',state,{httpOnly:true,sameSite:'lax',secure:process.env.NODE_ENV==='production'});res.redirect(oauth.generateAuthUrl({access_type:'offline',scope:['openid','email','profile'],state,hd:'kkumail.com'}))});
app.get('/auth/google/callback',async(req,res)=>{try{if(!req.query.code||req.query.state!==req.cookies.oauth_state)throw Error('Invalid OAuth state');const {tokens}=await oauth.getToken(req.query.code);const ticket=await oauth.verifyIdToken({idToken:tokens.id_token,audience:process.env.GOOGLE_CLIENT_ID});const p=ticket.getPayload();if(!p.email_verified||!domains.includes(p.hd)||!domains.some(d=>p.email.endsWith('@'+d)))throw Error('Only verified KKU accounts are allowed');const {rows}=await pool.query('INSERT INTO users(email,name,google_sub) VALUES($1,$2,$3) ON CONFLICT(email) DO UPDATE SET name=EXCLUDED.name,google_sub=EXCLUDED.google_sub RETURNING id,role,email,name',[p.email,p.name,p.sub]);const u=rows[0],payload={id:u.id,email:u.email,role:u.role,name:u.name,iat:Date.now()};const token=jwt.sign(payload,process.env.SESSION_SECRET,{expiresIn:u.role==='admin'?'30m':'24h'});res.cookie('access_token',token,{httpOnly:true,secure:process.env.NODE_ENV==='production',sameSite:'strict',maxAge:u.role==='admin'?1800000:86400000});res.cookie('csrf',crypto.randomBytes(24).toString('hex'),{httpOnly:false,secure:process.env.NODE_ENV==='production',sameSite:'strict'});res.redirect('http://localhost:5173') }catch(e){res.status(403).send(e.message)}});
app.get('/api/me',auth,(req,res)=>res.json({user:req.user}));app.get('/api/reports',auth,async(req,res)=>{const {rows}=await pool.query(req.user.role==='admin'?'SELECT * FROM reports ORDER BY created_at DESC':'SELECT id,plate_number,description,incident_datetime,status,ai_confidence,created_at FROM reports WHERE reporter_id=$1 ORDER BY created_at DESC',[req.user.id]);res.json({reports:rows})});
app.post('/api/reports',auth,reportLimit,csrf,upload.single('evidence'),async(req,res)=>{const {plateNumber,description,latitude,longitude,incidentDatetime}=req.body;if(!req.file)return res.status(400).json({error:'Evidence image is required'});if(new Date(incidentDatetime)>new Date()||new Date(incidentDatetime)<new Date(Date.now()-(+(process.env.MAX_INCIDENT_DAYS)||30)*86400000))return res.status(400).json({error:'Incident date is outside allowed range'});const sha=crypto.createHash('sha256').update(req.file.buffer).digest('hex');const {rows}=await pool.query('INSERT INTO reports(reporter_id,plate_number,description,latitude,longitude,incident_datetime,evidence_sha256,evidence_mime,status) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING *',[req.user.id,plateNumber||null,description,latitude||null,longitude||null,incidentDatetime,sha,req.file.mimetype,'PENDING']);await pool.query('INSERT INTO audit_logs(actor_id,action,entity_id,metadata) VALUES($1,$2,$3,$4)',[req.user.id,'REPORT_CREATED',rows[0].id,JSON.stringify({sha})]);res.status(201).json({report:rows[0],message:'Report queued for AI/manual verification'})});
app.patch('/api/reports/:id/status',auth,csrf,async(req,res)=>{if(req.user.role!=='admin')return res.sendStatus(403);const status=['APPROVED','REJECTED','REQUEST_INFO'].includes(req.body.status)?req.body.status:null;if(!status)return res.sendStatus(400);const {rows}=await pool.query('UPDATE reports SET status=$1,reviewed_by=$2,reviewed_at=now() WHERE id=$3 RETURNING *',[status,req.user.id,req.params.id]);await pool.query('INSERT INTO audit_logs(actor_id,action,entity_id,metadata) VALUES($1,$2,$3,$4)',[req.user.id,'STATUS_CHANGED',req.params.id,JSON.stringify({status})]);res.json({report:rows[0]})});
app.get('/',(_,res)=>res.sendFile(path.join(__dirname,'..','index.html')));
if(require.main===module)app.listen(process.env.PORT||4000,()=>console.log('KKU Parking app running on http://localhost:'+ (process.env.PORT||4000)));
module.exports=app;
